eureka:
  client:
    enabled: false

spring:
  config:
    activate:
      on-profile: prod
  application:
    name: ordering-service
  redis:
    host: redis-service
    port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/ordermsa?sslmode=disable
    username: postgres_admin
    password: ${DB_PW}
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true
  kafka:
    # prod = AWS MSK (KAFKA_SERVERS 환경변수로 bootstrap brokers 주입)
    kafka-server: ${KAFKA_SERVERS}

product-service:
  url: "http://product-service" # 쿠베 서비스 이름으로 바로 호출